version: '3'
services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    environment:
      - VOICEVOX_CPU_NUM_THREADS=4
    restart: unless-stopped
  bot:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - voicevox

volumes:
  deno-cache: 