version: '3'
services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-engine
    ports:
      - "50021:50021"
    environment:
      - VOICEVOX_CPU_NUM_THREADS=4
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/version", "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  bot:
    build: .
    container_name: discord-bot
    env_file:
      - .env
    environment:
      - VOICEVOX_API_URL=http://voicevox-engine:50021
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - voicevox

networks:
  app-network:
    driver: bridge