version: '3'
services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    environment:
      - VOICEVOX_CPU_NUM_THREADS=4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  bot:
    build: .
    env_file:
      - .env
    environment:
      - VOICEVOX_API_URL=http://voicevox:50021
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
    depends_on:
      voicevox:
        condition: service_healthy